import { pipeline, env } from "https://cdn.jsdelivr.net/npm/@xenova/transformers@2.17.2"; env.allowLocalModels=false;
const fileEl=document.querySelector("#file"),choose=document.querySelector("#choose"),drop=document.querySelector("#drop"),work=document.querySelector("#work"),video=document.querySelector("#video"),generate=document.querySelector("#generate"),download=document.querySelector("#download"),status=document.querySelector("#status"),captions=document.querySelector("#captions");
let currentFile=null,resultSegments=[];
choose.onclick=e=>{e.preventDefault();fileEl.click()}; fileEl.onchange=()=>fileEl.files[0]&&load(fileEl.files[0]);
drop.ondragover=e=>{e.preventDefault()}; drop.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])load(e.dataTransfer.files[0])};
function load(f){if(!f.type.startsWith("video/"))return;currentFile=f;video.src=URL.createObjectURL(f);drop.classList.add("hidden");work.classList.remove("hidden");setStatus("Video loaded. Click Generate captions.")}
function setStatus(s,error=false){status.textContent=s;status.className="status"+(error?" error":"")}
generate.onclick=async()=>{generate.disabled=true;download.disabled=true;captions.innerHTML="";try{setStatus("Loading speech model… first time can take a while.");const transcriber=await pipeline("automatic-speech-recognition","Xenova/whisper-tiny.en",{progress_callback:p=>{if(p.status==="progress"&&p.progress)setStatus("Downloading speech model: "+Math.round(p.progress)+"%")}});setStatus("Preparing audio…");const audio=await extractAudio(currentFile);setStatus("Transcribing…");const out=await transcriber(audio,{chunk_length_s:30,stride_length_s:5,return_timestamps:true});resultSegments=normalise(out);render();download.disabled=!resultSegments.length;setStatus(resultSegments.length?"Done — "+resultSegments.length+" caption segments created.":"No speech detected.",!resultSegments.length)}catch(e){console.error(e);setStatus("Could not generate captions. Try Chrome/Edge with a short MP4.",true)}generate.disabled=false};
async function extractAudio(file){const ctx=new AudioContext(),buf=await ctx.decodeAudioData(await file.arrayBuffer()),mono=new Float32Array(buf.length);for(let c=0;c<buf.numberOfChannels;c++){const d=buf.getChannelData(c);for(let i=0;i<d.length;i++)mono[i]+=d[i]/buf.numberOfChannels}return{data:mono,sampling_rate:buf.sampleRate}}
function normalise(out){return(out.chunks||[]).map(c=>({start:c.timestamp?.[0]??0,end:c.timestamp?.[1]??((c.timestamp?.[0]??0)+3),text:(c.text||"").trim()})).filter(x=>x.text)}
function render(){captions.innerHTML=resultSegments.map((c,i)=>'<div class="caption"><div class="time">'+fmt(c.start)+' → '+fmt(c.end)+'</div><input data-i="'+i+'" value="'+esc(c.text)+'"></div>').join("");captions.querySelectorAll("input").forEach(x=>x.oninput=()=>resultSegments[x.dataset.i].text=x.value)}
function fmt(s){s=Math.max(0,s||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=Math.floor(s%60),ms=Math.floor((s%1)*1000);return String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(sec).padStart(2,"0")+","+String(ms).padStart(3,"0")}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
download.onclick=()=>{const body=resultSegments.map((c,i)=>(i+1)+"\n"+fmt(c.start)+" --> "+fmt(c.end)+"\n"+c.text+"\n").join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/plain;charset=utf-8"}));a.download="captions.srt";a.click()};